# Generated by Django 5.2.13 on 2026-04-28 09:45

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, unique=True)),
                ('team_members', models.TextField(help_text='List team members separated by commas')),
                ('domain', models.CharField(choices=[('AI', 'AI'), ('ML', 'ML'), ('IoT', 'IoT')], max_length=10)),
                ('marks', models.IntegerField(default=0)),
                ('guide', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='projects', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Milestone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('synopsis', models.FileField(blank=True, null=True, upload_to='milestones/', validators=[django.core.validators.FileExtensionValidator(['pdf', 'doc', 'docx', 'zip'])])),
                ('phase1', models.FileField(blank=True, null=True, upload_to='milestones/', validators=[django.core.validators.FileExtensionValidator(['pdf', 'doc', 'docx', 'zip'])])),
                ('phase2', models.FileField(blank=True, null=True, upload_to='milestones/', validators=[django.core.validators.FileExtensionValidator(['pdf', 'doc', 'docx', 'zip'])])),
                ('final_report', models.FileField(blank=True, null=True, upload_to='milestones/', validators=[django.core.validators.FileExtensionValidator(['pdf', 'doc', 'docx', 'zip'])])),
                ('publication', models.FileField(blank=True, null=True, upload_to='milestones/', validators=[django.core.validators.FileExtensionValidator(['pdf', 'doc', 'docx', 'zip'])])),
                ('project', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='milestone', to='projects.project')),
            ],
        ),
    ]
